# Generated by Django 4.2.2 on 2023-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
