# Generated by Django 4.2.2 on 2023-06-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_uploadpdf_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadpdf',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterField(
            model_name='uploadpdf',
            name='pdf_file',
            field=models.FileField(upload_to='media/files/'),
        ),
    ]
