# Generated by Django 4.2.2 on 2023-06-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_department', to='dashboard.employee'),
        ),
    ]
