# Generated by Django 4.2.2 on 2023-06-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_department_employee_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_pdf', to='dashboard.employee'),
        ),
    ]
